package com.arsen.core.event;

public enum EventType {
    BINARY_LOADED, ANALYSIS_STARTED, ANALYSIS_PROGRESS, ANALYSIS_COMPLETED, DISASSEMBLY_UPDATED, SYMBOL_ADDED, SYMBOL_RENAMED, COMMENT_ADDED, BOOKMARK_ADDED, PROJECT_SAVED, PROJECT_LOADED, NAVIGATION_CHANGED, ERROR_OCCURRED
}
